//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4918
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sampler {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sampler.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] ActionsInvoke {
            get {
                object obj = ResourceManager.GetObject("ActionsInvoke", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ActionsPlayAnimation {
            get {
                object obj = ResourceManager.GetObject("ActionsPlayAnimation", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ActionsPlaySound {
            get {
                object obj = ResourceManager.GetObject("ActionsPlaySound", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ActionsSet {
            get {
                object obj = ResourceManager.GetObject("ActionsSet", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] AnimationsCenterPoint {
            get {
                object obj = ResourceManager.GetObject("AnimationsCenterPoint", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationsCenterPointDunkingBirdBody {
            get {
                object obj = ResourceManager.GetObject("AnimationsCenterPointDunkingBirdBody", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationsCenterPointDunkingBirdLegs {
            get {
                object obj = ResourceManager.GetObject("AnimationsCenterPointDunkingBirdLegs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] AnimationsInterpolationsBezierHandles {
            get {
                object obj = ResourceManager.GetObject("AnimationsInterpolationsBezierHandles", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] AnimationsInterpolationsEaseInOut {
            get {
                object obj = ResourceManager.GetObject("AnimationsInterpolationsEaseInOut", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] AnimationsInterpolationsTypes {
            get {
                object obj = ResourceManager.GetObject("AnimationsInterpolationsTypes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationsInterpolationsTypesRaceHorse {
            get {
                object obj = ResourceManager.GetObject("AnimationsInterpolationsTypesRaceHorse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] AnimationsInterpolationsWeight {
            get {
                object obj = ResourceManager.GetObject("AnimationsInterpolationsWeight", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] AnimationsKeyframesAlpha {
            get {
                object obj = ResourceManager.GetObject("AnimationsKeyframesAlpha", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] AnimationsKeyframesColor {
            get {
                object obj = ResourceManager.GetObject("AnimationsKeyframesColor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] AnimationsKeyframesMixedSample {
            get {
                object obj = ResourceManager.GetObject("AnimationsKeyframesMixedSample", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] AnimationsKeyframesPosition {
            get {
                object obj = ResourceManager.GetObject("AnimationsKeyframesPosition", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] AnimationsKeyframesRotate {
            get {
                object obj = ResourceManager.GetObject("AnimationsKeyframesRotate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] AnimationsKeyframesScale {
            get {
                object obj = ResourceManager.GetObject("AnimationsKeyframesScale", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] AnimationsKeyframesSize {
            get {
                object obj = ResourceManager.GetObject("AnimationsKeyframesSize", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] AnimationsMergeAnimation {
            get {
                object obj = ResourceManager.GetObject("AnimationsMergeAnimation", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] AnimationsRelativeTo {
            get {
                object obj = ResourceManager.GetObject("AnimationsRelativeTo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] AnimationsSwitchAnimation {
            get {
                object obj = ResourceManager.GetObject("AnimationsSwitchAnimation", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] AnimationsTransformAnimationDelay {
            get {
                object obj = ResourceManager.GetObject("AnimationsTransformAnimationDelay", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] AnimationsTransformAnimationFilter {
            get {
                object obj = ResourceManager.GetObject("AnimationsTransformAnimationFilter", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] AnimationsTransformAnimationMagnitude {
            get {
                object obj = ResourceManager.GetObject("AnimationsTransformAnimationMagnitude", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] AnimationsTransformAnimationTimeScale {
            get {
                object obj = ResourceManager.GetObject("AnimationsTransformAnimationTimeScale", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] AnimationsTransformByAttributeAnimationDelay {
            get {
                object obj = ResourceManager.GetObject("AnimationsTransformByAttributeAnimationDelay", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] AnimationsTransformByAttributeAnimationMagnitude {
            get {
                object obj = ResourceManager.GetObject("AnimationsTransformByAttributeAnimationMagnitude", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] AnimationsTransformByAttributeAnimationOverride {
            get {
                object obj = ResourceManager.GetObject("AnimationsTransformByAttributeAnimationOverride", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] AnimationsTransformByAttributeAnimationTimeScale {
            get {
                object obj = ResourceManager.GetObject("AnimationsTransformByAttributeAnimationTimeScale", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] AnimationsTransformByAttributeAnimationValueTransformer {
            get {
                object obj = ResourceManager.GetObject("AnimationsTransformByAttributeAnimationValueTransformer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] AnimationsTypesAlpha {
            get {
                object obj = ResourceManager.GetObject("AnimationsTypesAlpha", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] AnimationsTypesContentChangeShowHide {
            get {
                object obj = ResourceManager.GetObject("AnimationsTypesContentChangeShowHide", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] AnimationsTypesGainLoseFocus {
            get {
                object obj = ResourceManager.GetObject("AnimationsTypesGainLoseFocus", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationsTypesGainLoseFocusBagBottom {
            get {
                object obj = ResourceManager.GetObject("AnimationsTypesGainLoseFocusBagBottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationsTypesGainLoseFocusBagTop {
            get {
                object obj = ResourceManager.GetObject("AnimationsTypesGainLoseFocusBagTop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationsTypesGainLoseFocusPeanut1 {
            get {
                object obj = ResourceManager.GetObject("AnimationsTypesGainLoseFocusPeanut1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationsTypesGainLoseFocusPeanut2 {
            get {
                object obj = ResourceManager.GetObject("AnimationsTypesGainLoseFocusPeanut2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationsTypesGainLoseFocusPeanut3 {
            get {
                object obj = ResourceManager.GetObject("AnimationsTypesGainLoseFocusPeanut3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] AnimationsTypesIdle {
            get {
                object obj = ResourceManager.GetObject("AnimationsTypesIdle", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] AnimationsTypesMixedSample {
            get {
                object obj = ResourceManager.GetObject("AnimationsTypesMixedSample", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] AnimationsTypesMove {
            get {
                object obj = ResourceManager.GetObject("AnimationsTypesMove", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] AnimationsTypesRotate {
            get {
                object obj = ResourceManager.GetObject("AnimationsTypesRotate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] AnimationsTypesScale {
            get {
                object obj = ResourceManager.GetObject("AnimationsTypesScale", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] AnimationsTypesShowHide {
            get {
                object obj = ResourceManager.GetObject("AnimationsTypesShowHide", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] AnimationsTypesSize {
            get {
                object obj = ResourceManager.GetObject("AnimationsTypesSize", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Media Center SDK Sampler.
        /// </summary>
        internal static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        internal static byte[] CodeDataModelItems {
            get {
                object obj = ResourceManager.GetObject("CodeDataModelItems", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CodeDataThreading {
            get {
                object obj = ResourceManager.GetObject("CodeDataThreading", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CodeDataVirtualization {
            get {
                object obj = ResourceManager.GetObject("CodeDataVirtualization", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Controls {
            get {
                object obj = ResourceManager.GetObject("Controls", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ControlsButton {
            get {
                object obj = ResourceManager.GetObject("ControlsButton", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ControlsColorPicker {
            get {
                object obj = ResourceManager.GetObject("ControlsColorPicker", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ControlsColorPickerWithConstants {
            get {
                object obj = ResourceManager.GetObject("ControlsColorPickerWithConstants", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ControlsEditbox {
            get {
                object obj = ResourceManager.GetObject("ControlsEditbox", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ControlsGreenBallButton {
            get {
                object obj = ResourceManager.GetObject("ControlsGreenBallButton", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ControlsGreenBallButtonDark {
            get {
                object obj = ResourceManager.GetObject("ControlsGreenBallButtonDark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ControlsGreenBallButtonGlow {
            get {
                object obj = ResourceManager.GetObject("ControlsGreenBallButtonGlow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ControlsGreenBallButtonLight {
            get {
                object obj = ResourceManager.GetObject("ControlsGreenBallButtonLight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ControlsGreenBallButtonShadow {
            get {
                object obj = ResourceManager.GetObject("ControlsGreenBallButtonShadow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] ControlsGroupHeader {
            get {
                object obj = ResourceManager.GetObject("ControlsGroupHeader", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ControlsJellyButton {
            get {
                object obj = ResourceManager.GetObject("ControlsJellyButton", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream ControlsJellyButtonAquaHover {
            get {
                return ResourceManager.GetStream("ControlsJellyButtonAquaHover", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream ControlsJellyButtonAquaSelected {
            get {
                return ResourceManager.GetStream("ControlsJellyButtonAquaSelected", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream ControlsJellyButtonAquaSelecting {
            get {
                return ResourceManager.GetStream("ControlsJellyButtonAquaSelecting", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ControlsJellyButtonBrownRectangle {
            get {
                object obj = ResourceManager.GetObject("ControlsJellyButtonBrownRectangle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ControlsJellyButtonRedRectangle {
            get {
                object obj = ResourceManager.GetObject("ControlsJellyButtonRedRectangle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] ControlsListMarquee {
            get {
                object obj = ResourceManager.GetObject("ControlsListMarquee", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ControlsMarquee {
            get {
                object obj = ResourceManager.GetObject("ControlsMarquee", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ControlsPropertyAndValue {
            get {
                object obj = ResourceManager.GetObject("ControlsPropertyAndValue", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ControlsRadioGroup {
            get {
                object obj = ResourceManager.GetObject("ControlsRadioGroup", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ControlsScrollingText {
            get {
                object obj = ResourceManager.GetObject("ControlsScrollingText", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ControlsSimpleButton {
            get {
                object obj = ResourceManager.GetObject("ControlsSimpleButton", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ControlsSimpleCheckBox {
            get {
                object obj = ResourceManager.GetObject("ControlsSimpleCheckBox", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ControlsSimpleClock {
            get {
                object obj = ResourceManager.GetObject("ControlsSimpleClock", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ControlsSimpleEditbox {
            get {
                object obj = ResourceManager.GetObject("ControlsSimpleEditbox", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ControlsSimpleRadioGroup {
            get {
                object obj = ResourceManager.GetObject("ControlsSimpleRadioGroup", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ControlsSimpleSpinner {
            get {
                object obj = ResourceManager.GetObject("ControlsSimpleSpinner", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ControlsSpinner {
            get {
                object obj = ResourceManager.GetObject("ControlsSpinner", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Default {
            get {
                object obj = ResourceManager.GetObject("Default", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] FocusFocusOrder {
            get {
                object obj = ResourceManager.GetObject("FocusFocusOrder", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] FocusNavigateInto {
            get {
                object obj = ResourceManager.GetObject("FocusNavigateInto", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FourBoxGraphic {
            get {
                object obj = ResourceManager.GetObject("FourBoxGraphic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FourBoxGraphicNoBorder {
            get {
                object obj = ResourceManager.GetObject("FourBoxGraphicNoBorder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FourBoxGraphicSmall {
            get {
                object obj = ResourceManager.GetObject("FourBoxGraphicSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FourBoxGraphicTransparent {
            get {
                object obj = ResourceManager.GetObject("FourBoxGraphicTransparent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FourBoxGraphicTransparentNoBorder {
            get {
                object obj = ResourceManager.GetObject("FourBoxGraphicTransparentNoBorder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] FunAlphabetSoup {
            get {
                object obj = ResourceManager.GetObject("FunAlphabetSoup", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] FunColumnExpansion {
            get {
                object obj = ResourceManager.GetObject("FunColumnExpansion", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] FundamentalsHelloWorld {
            get {
                object obj = ResourceManager.GetObject("FundamentalsHelloWorld", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] FundamentalsMarkupLibraries {
            get {
                object obj = ResourceManager.GetObject("FundamentalsMarkupLibraries", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] FundamentalsModelViewSeparation {
            get {
                object obj = ResourceManager.GetObject("FundamentalsModelViewSeparation", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] FundamentalsObjectModelAccess {
            get {
                object obj = ResourceManager.GetObject("FundamentalsObjectModelAccess", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] FundamentalsObjectPaths {
            get {
                object obj = ResourceManager.GetObject("FundamentalsObjectPaths", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] FundamentalsResourceAccess {
            get {
                object obj = ResourceManager.GetObject("FundamentalsResourceAccess", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] FundamentalsXMLSyntax {
            get {
                object obj = ResourceManager.GetObject("FundamentalsXMLSyntax", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] FunHelix {
            get {
                object obj = ResourceManager.GetObject("FunHelix", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] FunMelt {
            get {
                object obj = ResourceManager.GetObject("FunMelt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FunMeltGraphic {
            get {
                object obj = ResourceManager.GetObject("FunMeltGraphic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] FunMovement {
            get {
                object obj = ResourceManager.GetObject("FunMovement", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] FunOthello {
            get {
                object obj = ResourceManager.GetObject("FunOthello", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FunOthelloBlack {
            get {
                object obj = ResourceManager.GetObject("FunOthelloBlack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FunOthelloBlank {
            get {
                object obj = ResourceManager.GetObject("FunOthelloBlank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FunOthelloRed {
            get {
                object obj = ResourceManager.GetObject("FunOthelloRed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Menu.
        /// </summary>
        internal static string GoToMainMenu {
            get {
                return ResourceManager.GetString("GoToMainMenu", resourceCulture);
            }
        }
        
        internal static byte[] GraphicsAlignment {
            get {
                object obj = ResourceManager.GetObject("GraphicsAlignment", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GraphicsAlignmentDog {
            get {
                object obj = ResourceManager.GetObject("GraphicsAlignmentDog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GraphicsAlignmentDogTiny {
            get {
                object obj = ResourceManager.GetObject("GraphicsAlignmentDogTiny", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] GraphicsImage {
            get {
                object obj = ResourceManager.GetObject("GraphicsImage", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GraphicsImageRedRectangle {
            get {
                object obj = ResourceManager.GetObject("GraphicsImageRedRectangle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] GraphicsImageStringCast {
            get {
                object obj = ResourceManager.GetObject("GraphicsImageStringCast", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greetings and Salutations!.
        /// </summary>
        internal static string Greeting {
            get {
                return ResourceManager.GetString("Greeting", resourceCulture);
            }
        }
        
        internal static byte[] Header {
            get {
                object obj = ResourceManager.GetObject("Header", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] InputHandlersClickHandler {
            get {
                object obj = ResourceManager.GetObject("InputHandlersClickHandler", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] InputHandlersGesturePan {
            get {
                object obj = ResourceManager.GetObject("InputHandlersGesturePan", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] InputHandlersGesturePanEnabledScrolling {
            get {
                object obj = ResourceManager.GetObject("InputHandlersGesturePanEnabledScrolling", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] InputHandlersKeyHandler {
            get {
                object obj = ResourceManager.GetObject("InputHandlersKeyHandler", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] InputHandlersKeyHandlerAny {
            get {
                object obj = ResourceManager.GetObject("InputHandlersKeyHandlerAny", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] InputHandlersMouseWheelHandler {
            get {
                object obj = ResourceManager.GetObject("InputHandlersMouseWheelHandler", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] InputHandlersShortcutHandler {
            get {
                object obj = ResourceManager.GetObject("InputHandlersShortcutHandler", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] InputHandlersStagesHandling {
            get {
                object obj = ResourceManager.GetObject("InputHandlersStagesHandling", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] InputHandlersTypingHandler {
            get {
                object obj = ResourceManager.GetObject("InputHandlersTypingHandler", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] InputKeyFocus {
            get {
                object obj = ResourceManager.GetObject("InputKeyFocus", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] InputMouseFocus {
            get {
                object obj = ResourceManager.GetObject("InputMouseFocus", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap InputMouseFocusFlowerBlue {
            get {
                object obj = ResourceManager.GetObject("InputMouseFocusFlowerBlue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap InputMouseFocusFlowerGreen {
            get {
                object obj = ResourceManager.GetObject("InputMouseFocusFlowerGreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KeyboardNavigationArrowDown {
            get {
                object obj = ResourceManager.GetObject("KeyboardNavigationArrowDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KeyboardNavigationArrowLeft {
            get {
                object obj = ResourceManager.GetObject("KeyboardNavigationArrowLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KeyboardNavigationArrowRight {
            get {
                object obj = ResourceManager.GetObject("KeyboardNavigationArrowRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KeyboardNavigationArrowUp {
            get {
                object obj = ResourceManager.GetObject("KeyboardNavigationArrowUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KeyboardNavigationCenterGradient {
            get {
                object obj = ResourceManager.GetObject("KeyboardNavigationCenterGradient", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] KeyboardNavigationContain {
            get {
                object obj = ResourceManager.GetObject("KeyboardNavigationContain", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] KeyboardNavigationContainerFocus {
            get {
                object obj = ResourceManager.GetObject("KeyboardNavigationContainerFocus", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] KeyboardNavigationFlow {
            get {
                object obj = ResourceManager.GetObject("KeyboardNavigationFlow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] KeyboardNavigationGroups {
            get {
                object obj = ResourceManager.GetObject("KeyboardNavigationGroups", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] KeyboardNavigationRowColumn {
            get {
                object obj = ResourceManager.GetObject("KeyboardNavigationRowColumn", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] KeyboardNavigationWrap {
            get {
                object obj = ResourceManager.GetObject("KeyboardNavigationWrap", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Launch {
            get {
                return ResourceManager.GetStream("Launch", resourceCulture);
            }
        }
        
        internal static byte[] LayoutAnchor {
            get {
                object obj = ResourceManager.GetObject("LayoutAnchor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] LayoutAnchorToFocus {
            get {
                object obj = ResourceManager.GetObject("LayoutAnchorToFocus", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] LayoutBorder {
            get {
                object obj = ResourceManager.GetObject("LayoutBorder", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] LayoutCenter {
            get {
                object obj = ResourceManager.GetObject("LayoutCenter", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] LayoutDefault {
            get {
                object obj = ResourceManager.GetObject("LayoutDefault", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] LayoutFill {
            get {
                object obj = ResourceManager.GetObject("LayoutFill", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] LayoutForm {
            get {
                object obj = ResourceManager.GetObject("LayoutForm", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LayoutGraphic {
            get {
                object obj = ResourceManager.GetObject("LayoutGraphic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LayoutGraphicArrow {
            get {
                object obj = ResourceManager.GetObject("LayoutGraphicArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LayoutGraphicOutlineRounded {
            get {
                object obj = ResourceManager.GetObject("LayoutGraphicOutlineRounded", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] LayoutGrid {
            get {
                object obj = ResourceManager.GetObject("LayoutGrid", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] LayoutHorizontalFlow {
            get {
                object obj = ResourceManager.GetObject("LayoutHorizontalFlow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] LayoutMarginsPadding {
            get {
                object obj = ResourceManager.GetObject("LayoutMarginsPadding", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] LayoutMinimumSizeMaximumSize {
            get {
                object obj = ResourceManager.GetObject("LayoutMinimumSizeMaximumSize", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] LayoutRotate {
            get {
                object obj = ResourceManager.GetObject("LayoutRotate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] LayoutScale {
            get {
                object obj = ResourceManager.GetObject("LayoutScale", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] LayoutVerticalFlow {
            get {
                object obj = ResourceManager.GetObject("LayoutVerticalFlow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MarkupAccessibility {
            get {
                object obj = ResourceManager.GetObject("MarkupAccessibility", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MarkupAggregates {
            get {
                object obj = ResourceManager.GetObject("MarkupAggregates", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MarkupBaseUIs {
            get {
                object obj = ResourceManager.GetObject("MarkupBaseUIs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MarkupColorSchemes {
            get {
                object obj = ResourceManager.GetObject("MarkupColorSchemes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MarkupDebugging {
            get {
                object obj = ResourceManager.GetObject("MarkupDebugging", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MarkupGlobalization {
            get {
                object obj = ResourceManager.GetObject("MarkupGlobalization", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MarkupGlobalizationCart {
            get {
                object obj = ResourceManager.GetObject("MarkupGlobalizationCart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MarkupGlobalizationRaceHorse {
            get {
                object obj = ResourceManager.GetObject("MarkupGlobalizationRaceHorse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] MarkupHostViewItem {
            get {
                object obj = ResourceManager.GetObject("MarkupHostViewItem", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MarkupInvokeCommand {
            get {
                object obj = ResourceManager.GetObject("MarkupInvokeCommand", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MarkupLocals {
            get {
                object obj = ResourceManager.GetObject("MarkupLocals", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MarkupProperties {
            get {
                object obj = ResourceManager.GetObject("MarkupProperties", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MarkupResourceGroup {
            get {
                object obj = ResourceManager.GetObject("MarkupResourceGroup", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MarkupStringTableAccess {
            get {
                object obj = ResourceManager.GetObject("MarkupStringTableAccess", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ObjectModelAddInHostApplicationControlEnabled {
            get {
                object obj = ResourceManager.GetObject("ObjectModelAddInHostApplicationControlEnabled", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ObjectModelAddInHostEntryPointParameters {
            get {
                object obj = ResourceManager.GetObject("ObjectModelAddInHostEntryPointParameters", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ObjectModelAddInHostMetadataAccessEnabled {
            get {
                object obj = ResourceManager.GetObject("ObjectModelAddInHostMetadataAccessEnabled", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ObjectModelApplicationContextInstallApplication {
            get {
                object obj = ResourceManager.GetObject("ObjectModelApplicationContextInstallApplication", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ObjectModelApplicationContextIsCurrentlyVisible {
            get {
                object obj = ResourceManager.GetObject("ObjectModelApplicationContextIsCurrentlyVisible", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ObjectModelApplicationContextIsEntryPointRegistered {
            get {
                object obj = ResourceManager.GetObject("ObjectModelApplicationContextIsEntryPointRegistered", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ObjectModelApplicationContextIsForegroundApplication {
            get {
                object obj = ResourceManager.GetObject("ObjectModelApplicationContextIsForegroundApplication", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ObjectModelApplicationContextReturnToApplication {
            get {
                object obj = ResourceManager.GetObject("ObjectModelApplicationContextReturnToApplication", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ObjectModelApplicationContextSingleInstance {
            get {
                object obj = ResourceManager.GetObject("ObjectModelApplicationContextSingleInstance", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ObjectModelEnvironmentIsWidescreen {
            get {
                object obj = ResourceManager.GetObject("ObjectModelEnvironmentIsWidescreen", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ObjectModelHostingHistoryOrientedPageSession {
            get {
                object obj = ResourceManager.GetObject("ObjectModelHostingHistoryOrientedPageSession", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ObjectModelMediaCenterAddInHostMediaContextAlbum {
            get {
                object obj = ResourceManager.GetObject("ObjectModelMediaCenterAddInHostMediaContextAlbum", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ObjectModelMediaCenterAddInHostMediaContextArtist {
            get {
                object obj = ResourceManager.GetObject("ObjectModelMediaCenterAddInHostMediaContextArtist", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ObjectModelMediaCenterAddInHostMediaContextDVD {
            get {
                object obj = ResourceManager.GetObject("ObjectModelMediaCenterAddInHostMediaContextDVD", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ObjectModelMediaCenterAddInHostMediaContextGenre {
            get {
                object obj = ResourceManager.GetObject("ObjectModelMediaCenterAddInHostMediaContextGenre", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ObjectModelMediaCenterAddInHostMediaContextPicture {
            get {
                object obj = ResourceManager.GetObject("ObjectModelMediaCenterAddInHostMediaContextPicture", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ObjectModelMediaCenterAddInHostMediaContextPlaylist {
            get {
                object obj = ResourceManager.GetObject("ObjectModelMediaCenterAddInHostMediaContextPlaylist", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ObjectModelMediaCenterAddInHostMediaContextSong {
            get {
                object obj = ResourceManager.GetObject("ObjectModelMediaCenterAddInHostMediaContextSong", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ObjectModelMediaCenterAddInHostMediaContextTV {
            get {
                object obj = ResourceManager.GetObject("ObjectModelMediaCenterAddInHostMediaContextTV", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ObjectModelMediaCenterAddInHostMediaContextVideo {
            get {
                object obj = ResourceManager.GetObject("ObjectModelMediaCenterAddInHostMediaContextVideo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ObjectModelMediaCenterAudioMixer {
            get {
                object obj = ResourceManager.GetObject("ObjectModelMediaCenterAudioMixer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ObjectModelMediaCenterBackgroundModes {
            get {
                object obj = ResourceManager.GetObject("ObjectModelMediaCenterBackgroundModes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ObjectModelMediaCenterEnvironmentCapabilities {
            get {
                object obj = ResourceManager.GetObject("ObjectModelMediaCenterEnvironmentCapabilities", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ObjectModelMediaCenterEnvironmentCpuClass {
            get {
                object obj = ResourceManager.GetObject("ObjectModelMediaCenterEnvironmentCpuClass", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ObjectModelMediaCenterEnvironmentCreateDesktopShortcut {
            get {
                object obj = ResourceManager.GetObject("ObjectModelMediaCenterEnvironmentCreateDesktopShortcut", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ObjectModelMediaCenterEnvironmentCurrentCulture {
            get {
                object obj = ResourceManager.GetObject("ObjectModelMediaCenterEnvironmentCurrentCulture", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ObjectModelMediaCenterEnvironmentDialog {
            get {
                object obj = ResourceManager.GetObject("ObjectModelMediaCenterEnvironmentDialog", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ObjectModelMediaCenterEnvironmentDialogNotification {
            get {
                object obj = ResourceManager.GetObject("ObjectModelMediaCenterEnvironmentDialogNotification", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ObjectModelMediaCenterEnvironmentLaunchEntryPoint {
            get {
                object obj = ResourceManager.GetObject("ObjectModelMediaCenterEnvironmentLaunchEntryPoint", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ObjectModelMediaCenterEnvironmentNavigateToPage {
            get {
                object obj = ResourceManager.GetObject("ObjectModelMediaCenterEnvironmentNavigateToPage", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ObjectModelMediaCenterEnvironmentPlayMediaAudio {
            get {
                object obj = ResourceManager.GetObject("ObjectModelMediaCenterEnvironmentPlayMediaAudio", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ObjectModelMediaCenterEnvironmentPlayMediaVideo {
            get {
                object obj = ResourceManager.GetObject("ObjectModelMediaCenterEnvironmentPlayMediaVideo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ObjectModelMediaCenterEnvironmentShowOnScreenKeyboard {
            get {
                object obj = ResourceManager.GetObject("ObjectModelMediaCenterEnvironmentShowOnScreenKeyboard", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ObjectModelMediaCenterEnvironmentVersion {
            get {
                object obj = ResourceManager.GetObject("ObjectModelMediaCenterEnvironmentVersion", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ObjectModelMediaCenterMediaCollectionAddItem {
            get {
                object obj = ResourceManager.GetObject("ObjectModelMediaCenterMediaCollectionAddItem", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ObjectModelMediaCenterMediaCollectionAddItemRepeater {
            get {
                object obj = ResourceManager.GetObject("ObjectModelMediaCenterMediaCollectionAddItemRepeater", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ObjectModelMediaCenterMediaCollectionBasic {
            get {
                object obj = ResourceManager.GetObject("ObjectModelMediaCenterMediaCollectionBasic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ObjectModelMediaCenterMediaCollectionMixed {
            get {
                object obj = ResourceManager.GetObject("ObjectModelMediaCenterMediaCollectionMixed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ObjectModelMediaExperienceEntryPointID {
            get {
                object obj = ResourceManager.GetObject("ObjectModelMediaExperienceEntryPointID", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ObjectModelMediaExperienceGoToFullscreen {
            get {
                object obj = ResourceManager.GetObject("ObjectModelMediaExperienceGoToFullscreen", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ObjectModelMediaExperienceMediaMetadataSong {
            get {
                object obj = ResourceManager.GetObject("ObjectModelMediaExperienceMediaMetadataSong", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ObjectModelMediaExperienceMediaMetadataVideo {
            get {
                object obj = ResourceManager.GetObject("ObjectModelMediaExperienceMediaMetadataVideo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ObjectModelMediaExperienceMediaType {
            get {
                object obj = ResourceManager.GetObject("ObjectModelMediaExperienceMediaType", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ObjectModelMediaExperienceTransport {
            get {
                object obj = ResourceManager.GetObject("ObjectModelMediaExperienceTransport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ObjectModelMediaExperienceUrl {
            get {
                object obj = ResourceManager.GetObject("ObjectModelMediaExperienceUrl", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ObjectModelNavigateAndNavigateCommand {
            get {
                object obj = ResourceManager.GetObject("ObjectModelNavigateAndNavigateCommand", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] RepeaterContentSelectors {
            get {
                object obj = ResourceManager.GetObject("RepeaterContentSelectors", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RepeaterContentSelectorsCD {
            get {
                object obj = ResourceManager.GetObject("RepeaterContentSelectorsCD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RepeaterDivider {
            get {
                object obj = ResourceManager.GetObject("RepeaterDivider", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] RepeaterDividers {
            get {
                object obj = ResourceManager.GetObject("RepeaterDividers", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] RepeaterFlowLayout {
            get {
                object obj = ResourceManager.GetObject("RepeaterFlowLayout", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RepeaterFlowLayoutBlueStar {
            get {
                object obj = ResourceManager.GetObject("RepeaterFlowLayoutBlueStar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RepeaterFlowLayoutGreenStar {
            get {
                object obj = ResourceManager.GetObject("RepeaterFlowLayoutGreenStar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RepeaterFlowLayoutPurpleStar {
            get {
                object obj = ResourceManager.GetObject("RepeaterFlowLayoutPurpleStar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RepeaterFlowLayoutYellowStar {
            get {
                object obj = ResourceManager.GetObject("RepeaterFlowLayoutYellowStar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] RepeaterGridLayout {
            get {
                object obj = ResourceManager.GetObject("RepeaterGridLayout", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RepeaterGridLayoutBlueStar {
            get {
                object obj = ResourceManager.GetObject("RepeaterGridLayoutBlueStar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RepeaterGridLayoutGreenStar {
            get {
                object obj = ResourceManager.GetObject("RepeaterGridLayoutGreenStar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RepeaterGridLayoutPurpleStar {
            get {
                object obj = ResourceManager.GetObject("RepeaterGridLayoutPurpleStar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RepeaterGridLayoutYellowStar {
            get {
                object obj = ResourceManager.GetObject("RepeaterGridLayoutYellowStar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] RepeaterListDataSet {
            get {
                object obj = ResourceManager.GetObject("RepeaterListDataSet", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] RepeaterRepeaterViewItem {
            get {
                object obj = ResourceManager.GetObject("RepeaterRepeaterViewItem", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] RulesBinding {
            get {
                object obj = ResourceManager.GetObject("RulesBinding", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] RulesChanged {
            get {
                object obj = ResourceManager.GetObject("RulesChanged", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] RulesCondition {
            get {
                object obj = ResourceManager.GetObject("RulesCondition", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] RulesCustomRuleEqualityCondition {
            get {
                object obj = ResourceManager.GetObject("RulesCustomRuleEqualityCondition", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] RulesCustomRuleModifiedCondition {
            get {
                object obj = ResourceManager.GetObject("RulesCustomRuleModifiedCondition", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] RulesDefault {
            get {
                object obj = ResourceManager.GetObject("RulesDefault", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] RulesIsTypeCondition {
            get {
                object obj = ResourceManager.GetObject("RulesIsTypeCondition", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] RulesIsValidCondition {
            get {
                object obj = ResourceManager.GetObject("RulesIsValidCondition", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] RulesMixedSample {
            get {
                object obj = ResourceManager.GetObject("RulesMixedSample", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Sampler {
            get {
                object obj = ResourceManager.GetObject("Sampler", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] Samples {
            get {
                object obj = ResourceManager.GetObject("Samples", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ScrollingLists {
            get {
                object obj = ResourceManager.GetObject("ScrollingLists", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ScrollingListsXbox360 {
            get {
                object obj = ResourceManager.GetObject("ScrollingListsXbox360", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] ScrollingLocking {
            get {
                object obj = ResourceManager.GetObject("ScrollingLocking", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ScrollingLockingPurpleStar {
            get {
                object obj = ResourceManager.GetObject("ScrollingLockingPurpleStar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ScrollingLockingYellowStar {
            get {
                object obj = ResourceManager.GetObject("ScrollingLockingYellowStar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] ScrollingPadding {
            get {
                object obj = ResourceManager.GetObject("ScrollingPadding", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ScrollingPaddingPurpleStar {
            get {
                object obj = ResourceManager.GetObject("ScrollingPaddingPurpleStar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ScrollingPaddingPurpleStar1 {
            get {
                object obj = ResourceManager.GetObject("ScrollingPaddingPurpleStar1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ScrollingPaddingYellowStar {
            get {
                object obj = ResourceManager.GetObject("ScrollingPaddingYellowStar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ScrollingPaddingYellowStar1 {
            get {
                object obj = ResourceManager.GetObject("ScrollingPaddingYellowStar1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] ScrollingScrollerViewItem {
            get {
                object obj = ResourceManager.GetObject("ScrollingScrollerViewItem", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ScrollingStaticContent {
            get {
                object obj = ResourceManager.GetObject("ScrollingStaticContent", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Styles {
            get {
                object obj = ResourceManager.GetObject("Styles", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SystemTextStringBuilder {
            get {
                object obj = ResourceManager.GetObject("SystemTextStringBuilder", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Test {
            get {
                object obj = ResourceManager.GetObject("Test", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] TransformersBooleanTransformer {
            get {
                object obj = ResourceManager.GetObject("TransformersBooleanTransformer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] TransformersDateTimeTransformer {
            get {
                object obj = ResourceManager.GetObject("TransformersDateTimeTransformer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] TransformersFormatTransformer {
            get {
                object obj = ResourceManager.GetObject("TransformersFormatTransformer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] TransformersMathTransformer {
            get {
                object obj = ResourceManager.GetObject("TransformersMathTransformer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] TransformersTimeSpanTransformer {
            get {
                object obj = ResourceManager.GetObject("TransformersTimeSpanTransformer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ViewItemsClip {
            get {
                object obj = ResourceManager.GetObject("ViewItemsClip", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ViewItemsClipAlpha {
            get {
                object obj = ResourceManager.GetObject("ViewItemsClipAlpha", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ViewItemsClipColorFilter {
            get {
                object obj = ResourceManager.GetObject("ViewItemsClipColorFilter", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ViewItemsClipColorMask {
            get {
                object obj = ResourceManager.GetObject("ViewItemsClipColorMask", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ViewItemsClipFadeAmount {
            get {
                object obj = ResourceManager.GetObject("ViewItemsClipFadeAmount", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ViewItemsClipFadeSize {
            get {
                object obj = ResourceManager.GetObject("ViewItemsClipFadeSize", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ViewItemsClipOffsets {
            get {
                object obj = ResourceManager.GetObject("ViewItemsClipOffsets", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ViewItemsClipOrientation {
            get {
                object obj = ResourceManager.GetObject("ViewItemsClipOrientation", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ViewItemsClipRotation {
            get {
                object obj = ResourceManager.GetObject("ViewItemsClipRotation", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ViewItemsClipShowFade {
            get {
                object obj = ResourceManager.GetObject("ViewItemsClipShowFade", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ViewItemsColorFill {
            get {
                object obj = ResourceManager.GetObject("ViewItemsColorFill", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ViewItemsColorFillColors {
            get {
                object obj = ResourceManager.GetObject("ViewItemsColorFillColors", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ViewItemsDateTimeTransformerDatesBasic {
            get {
                object obj = ResourceManager.GetObject("ViewItemsDateTimeTransformerDatesBasic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ViewItemsDateTimeTransformerDatesComplex {
            get {
                object obj = ResourceManager.GetObject("ViewItemsDateTimeTransformerDatesComplex", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ViewItemsDateTimeTransformerTimes {
            get {
                object obj = ResourceManager.GetObject("ViewItemsDateTimeTransformerTimes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ViewItemsFormatTransformer {
            get {
                object obj = ResourceManager.GetObject("ViewItemsFormatTransformer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ViewItemsGraphic {
            get {
                object obj = ResourceManager.GetObject("ViewItemsGraphic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ViewItemsGraphicAcquiringImageHTTP {
            get {
                object obj = ResourceManager.GetObject("ViewItemsGraphicAcquiringImageHTTP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ViewItemsGraphicDog {
            get {
                object obj = ResourceManager.GetObject("ViewItemsGraphicDog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ViewItemsGraphicDogSmall {
            get {
                object obj = ResourceManager.GetObject("ViewItemsGraphicDogSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] ViewItemsGraphicFromCode {
            get {
                object obj = ResourceManager.GetObject("ViewItemsGraphicFromCode", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ViewItemsNowPlaying {
            get {
                object obj = ResourceManager.GetObject("ViewItemsNowPlaying", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ViewItemsNowPlayingIsActive {
            get {
                object obj = ResourceManager.GetObject("ViewItemsNowPlayingIsActive", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ViewItemsNowPlayingMetadata {
            get {
                object obj = ResourceManager.GetObject("ViewItemsNowPlayingMetadata", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ViewItemsPanel {
            get {
                object obj = ResourceManager.GetObject("ViewItemsPanel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ViewItemsScrollingDataLockedHorizontal {
            get {
                object obj = ResourceManager.GetObject("ViewItemsScrollingDataLockedHorizontal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ViewItemsScrollingDataLockedVertical {
            get {
                object obj = ResourceManager.GetObject("ViewItemsScrollingDataLockedVertical", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ViewItemsScrollingDataNoRepeaterHorizontal {
            get {
                object obj = ResourceManager.GetObject("ViewItemsScrollingDataNoRepeaterHorizontal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ViewItemsScrollingDataNoRepeaterVertical {
            get {
                object obj = ResourceManager.GetObject("ViewItemsScrollingDataNoRepeaterVertical", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ViewItemsScrollingDataPaddingHorizontal {
            get {
                object obj = ResourceManager.GetObject("ViewItemsScrollingDataPaddingHorizontal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ViewItemsScrollingDataPaddingVertical {
            get {
                object obj = ResourceManager.GetObject("ViewItemsScrollingDataPaddingVertical", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ViewItemsScrollingDataPageStepNoRepeater {
            get {
                object obj = ResourceManager.GetObject("ViewItemsScrollingDataPageStepNoRepeater", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ViewItemsScrollingDataRelativePaddingFar {
            get {
                object obj = ResourceManager.GetObject("ViewItemsScrollingDataRelativePaddingFar", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ViewItemsScrollingDataRelativePaddingNear {
            get {
                object obj = ResourceManager.GetObject("ViewItemsScrollingDataRelativePaddingNear", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ViewItemsScrollingDataRepeaterHorizontal {
            get {
                object obj = ResourceManager.GetObject("ViewItemsScrollingDataRepeaterHorizontal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ViewItemsScrollingDataRepeaterVertical {
            get {
                object obj = ResourceManager.GetObject("ViewItemsScrollingDataRepeaterVertical", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ViewItemsScrollingDataScrollStepNoRepeater {
            get {
                object obj = ResourceManager.GetObject("ViewItemsScrollingDataScrollStepNoRepeater", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ViewItemsSecureEditableText {
            get {
                object obj = ResourceManager.GetObject("ViewItemsSecureEditableText", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ViewItemsText {
            get {
                object obj = ResourceManager.GetObject("ViewItemsText", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ViewItemsTextAlignment {
            get {
                object obj = ResourceManager.GetObject("ViewItemsTextAlignment", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ViewItemsTextBackGroundColor {
            get {
                object obj = ResourceManager.GetObject("ViewItemsTextBackGroundColor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ViewItemsTextBigFontCharacter {
            get {
                object obj = ResourceManager.GetObject("ViewItemsTextBigFontCharacter", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ViewItemsTextColor {
            get {
                object obj = ResourceManager.GetObject("ViewItemsTextColor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ViewItemsTextContent {
            get {
                object obj = ResourceManager.GetObject("ViewItemsTextContent", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ViewItemsTextFont {
            get {
                object obj = ResourceManager.GetObject("ViewItemsTextFont", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ViewItemsTextMaxLines {
            get {
                object obj = ResourceManager.GetObject("ViewItemsTextMaxLines", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ViewItemsTextWordWrap {
            get {
                object obj = ResourceManager.GetObject("ViewItemsTextWordWrap", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ViewItemsTimeSpanTransformer {
            get {
                object obj = ResourceManager.GetObject("ViewItemsTimeSpanTransformer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ViewItemsVideo {
            get {
                object obj = ResourceManager.GetObject("ViewItemsVideo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ViewItemsVideoCrackedTube {
            get {
                object obj = ResourceManager.GetObject("ViewItemsVideoCrackedTube", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream ViewItemsVideoGlassBreaking {
            get {
                return ResourceManager.GetStream("ViewItemsVideoGlassBreaking", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ViewItemsVideoTV {
            get {
                object obj = ResourceManager.GetObject("ViewItemsVideoTV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WhiteGraphic {
            get {
                object obj = ResourceManager.GetObject("WhiteGraphic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WhiteGraphicSmall {
            get {
                object obj = ResourceManager.GetObject("WhiteGraphicSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
