//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3506
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace McmlPadAuto {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("McmlPadAuto.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string StringAbout {
            get {
                return ResourceManager.GetString("StringAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Browse.
        /// </summary>
        internal static string StringButtonBrowse {
            get {
                return ResourceManager.GetString("StringButtonBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Go.
        /// </summary>
        internal static string StringButtonGo {
            get {
                return ResourceManager.GetString("StringButtonGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright Microsoft Corporation.
        /// </summary>
        internal static string StringCopyright {
            get {
                return ResourceManager.GetString("StringCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem.
        /// </summary>
        internal static string StringDialogCaptionProblem {
            get {
                return ResourceManager.GetString("StringDialogCaptionProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string StringLabelHistory {
            get {
                return ResourceManager.GetString("StringLabelHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URI.
        /// </summary>
        internal static string StringLabelURI {
            get {
                return ResourceManager.GetString("StringLabelURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error launching McmlPad.exe.{0}.
        /// </summary>
        internal static string StringMCMLPadLaunchError {
            get {
                return ResourceManager.GetString("StringMCMLPadLaunchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate McmlPad.exe.  File expected in &apos;{0}&apos;..
        /// </summary>
        internal static string StringMCMLPadNotFound {
            get {
                return ResourceManager.GetString("StringMCMLPadNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview Tool Launcher.
        /// </summary>
        internal static string StringMCMLPreviewToolLauncher {
            get {
                return ResourceManager.GetString("StringMCMLPreviewToolLauncher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;About.
        /// </summary>
        internal static string StringMenuAbout {
            get {
                return ResourceManager.GetString("StringMenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Clear History.
        /// </summary>
        internal static string StringMenuClearHistory {
            get {
                return ResourceManager.GetString("StringMenuClearHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File.
        /// </summary>
        internal static string StringMenuFile {
            get {
                return ResourceManager.GetString("StringMenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        internal static string StringMenuHelp {
            get {
                return ResourceManager.GetString("StringMenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open History.
        /// </summary>
        internal static string StringMenuOpenHistory {
            get {
                return ResourceManager.GetString("StringMenuOpenHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Options.
        /// </summary>
        internal static string StringMenuOptions {
            get {
                return ResourceManager.GetString("StringMenuOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Use Single Preview Tool Instance.
        /// </summary>
        internal static string StringMenuReusePad {
            get {
                return ResourceManager.GetString("StringMenuReusePad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save History.
        /// </summary>
        internal static string StringMenuSaveHistory {
            get {
                return ResourceManager.GetString("StringMenuSaveHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t write to the folder in which MCMLPadAuto is located. Settings and history will not be persisted..
        /// </summary>
        internal static string StringUnauthorizedAccessException {
            get {
                return ResourceManager.GetString("StringUnauthorizedAccessException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Media Center Software Development Kit.
        /// </summary>
        internal static string StringWindowsMediaCenterSDK {
            get {
                return ResourceManager.GetString("StringWindowsMediaCenterSDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCMLPadAuto History.
        /// </summary>
        internal static string StringXMLElementMCMLPadHistory {
            get {
                return ResourceManager.GetString("StringXMLElementMCMLPadHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCMLPadAuto Settings.
        /// </summary>
        internal static string StringXMLElementMCMLPadSettings {
            get {
                return ResourceManager.GetString("StringXMLElementMCMLPadSettings", resourceCulture);
            }
        }
    }
}
