//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4913
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Z {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Z.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Background {
            get {
                object obj = ResourceManager.GetObject("Background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BackgroundItem1 {
            get {
                object obj = ResourceManager.GetObject("BackgroundItem1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BackgroundItem2 {
            get {
                object obj = ResourceManager.GetObject("BackgroundItem2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] BackgroundLayer {
            get {
                object obj = ResourceManager.GetObject("BackgroundLayer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Button {
            get {
                object obj = ResourceManager.GetObject("Button", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonFocus {
            get {
                object obj = ResourceManager.GetObject("ButtonFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonNonFocus {
            get {
                object obj = ResourceManager.GetObject("ButtonNonFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] CheckBox {
            get {
                object obj = ResourceManager.GetObject("CheckBox", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CheckBoxChecked {
            get {
                object obj = ResourceManager.GetObject("CheckBoxChecked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CheckBoxFocus {
            get {
                object obj = ResourceManager.GetObject("CheckBoxFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CheckBoxNonFocus {
            get {
                object obj = ResourceManager.GetObject("CheckBoxNonFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Container {
            get {
                object obj = ResourceManager.GetObject("Container", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] ContentList {
            get {
                object obj = ResourceManager.GetObject("ContentList", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CoreControls {
            get {
                object obj = ResourceManager.GetObject("CoreControls", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Default {
            get {
                object obj = ResourceManager.GetObject("Default", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DetailsPage {
            get {
                object obj = ResourceManager.GetObject("DetailsPage", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Manager Not Available.
        /// </summary>
        internal static string DownloadFailedDialog_Caption {
            get {
                return ResourceManager.GetString("DownloadFailedDialog_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Download Manager Service has not been installed;  downloads not possible..
        /// </summary>
        internal static string DownloadFailedDialog_Text {
            get {
                return ResourceManager.GetString("DownloadFailedDialog_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads.
        /// </summary>
        internal static string Downloads {
            get {
                return ResourceManager.GetString("Downloads", resourceCulture);
            }
        }
        
        internal static byte[] DownloadsPage {
            get {
                object obj = ResourceManager.GetObject("DownloadsPage", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] EditBox {
            get {
                object obj = ResourceManager.GetObject("EditBox", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EditBoxFocus {
            get {
                object obj = ResourceManager.GetObject("EditBoxFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EditBoxNonFocus {
            get {
                object obj = ResourceManager.GetObject("EditBoxNonFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] EditBoxWithKeyboard {
            get {
                object obj = ResourceManager.GetObject("EditBoxWithKeyboard", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] FilterList {
            get {
                object obj = ResourceManager.GetObject("FilterList", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Footer {
            get {
                object obj = ResourceManager.GetObject("Footer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GalleryFocus {
            get {
                object obj = ResourceManager.GetObject("GalleryFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] GalleryPage {
            get {
                object obj = ResourceManager.GetObject("GalleryPage", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Gradient_Bottom {
            get {
                object obj = ResourceManager.GetObject("Gradient_Bottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Gradient_Top {
            get {
                object obj = ResourceManager.GetObject("Gradient_Top", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] Header {
            get {
                object obj = ResourceManager.GetObject("Header", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Keyboard {
            get {
                object obj = ResourceManager.GetObject("Keyboard", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] KeyboardContents {
            get {
                object obj = ResourceManager.GetObject("KeyboardContents", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] KeyboardPage {
            get {
                object obj = ResourceManager.GetObject("KeyboardPage", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] LogInPage {
            get {
                object obj = ResourceManager.GetObject("LogInPage", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MainMenu {
            get {
                object obj = ResourceManager.GetObject("MainMenu", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MouseNavDown {
            get {
                object obj = ResourceManager.GetObject("MouseNavDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MouseNavDownFocus {
            get {
                object obj = ResourceManager.GetObject("MouseNavDownFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MouseNavLeft {
            get {
                object obj = ResourceManager.GetObject("MouseNavLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MouseNavLeftFocus {
            get {
                object obj = ResourceManager.GetObject("MouseNavLeftFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MouseNavRight {
            get {
                object obj = ResourceManager.GetObject("MouseNavRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MouseNavRightFocus {
            get {
                object obj = ResourceManager.GetObject("MouseNavRightFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MouseNavUp {
            get {
                object obj = ResourceManager.GetObject("MouseNavUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MouseNavUpFocus {
            get {
                object obj = ResourceManager.GetObject("MouseNavUpFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movies.
        /// </summary>
        internal static string Movies {
            get {
                return ResourceManager.GetString("Movies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view all {0} movies.
        /// </summary>
        internal static string Movies_Category_SubTitle {
            get {
                return ResourceManager.GetString("Movies_Category_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///cast: {1}
        ///{2} min, {3}, {4}.
        /// </summary>
        internal static string Movies_Details_Metadata {
            get {
                return ResourceManager.GetString("Movies_Details_Metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to preview.
        /// </summary>
        internal static string Movies_Details_Preview {
            get {
                return ResourceManager.GetString("Movies_Details_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Movie.
        /// </summary>
        internal static string Movies_DownloadDialog_Caption {
            get {
                return ResourceManager.GetString("Movies_DownloadDialog_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; has been added to your download queue..
        /// </summary>
        internal static string Movies_DownloadDialog_Text {
            get {
                return ResourceManager.GetString("Movies_DownloadDialog_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all.
        /// </summary>
        internal static string Movies_Filter_All {
            get {
                return ResourceManager.GetString("Movies_Filter_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///cast: {1}.
        /// </summary>
        internal static string Movies_Search_Metadata1 {
            get {
                return ResourceManager.GetString("Movies_Search_Metadata1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {2} min, {3}, {4}.
        /// </summary>
        internal static string Movies_Search_Metadata2 {
            get {
                return ResourceManager.GetString("Movies_Search_Metadata2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie.
        /// </summary>
        internal static string Movies_Search_Type {
            get {
                return ResourceManager.GetString("Movies_Search_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        internal static string Music {
            get {
                return ResourceManager.GetString("Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This track has been added to your queue..
        /// </summary>
        internal static string Music_PlayDialog_Text {
            get {
                return ResourceManager.GetString("Music_PlayDialog_Text", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap MusicDirectory {
            get {
                object obj = ResourceManager.GetObject("MusicDirectory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MusicFile {
            get {
                object obj = ResourceManager.GetObject("MusicFile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] ProgressBar {
            get {
                object obj = ResourceManager.GetObject("ProgressBar", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ProgressBarFocus {
            get {
                object obj = ResourceManager.GetObject("ProgressBarFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ProgressBarNonFocus {
            get {
                object obj = ResourceManager.GetObject("ProgressBarNonFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] SampleData {
            get {
                object obj = ResourceManager.GetObject("SampleData", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        internal static byte[] SearchPage {
            get {
                object obj = ResourceManager.GetObject("SearchPage", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SearchResult {
            get {
                object obj = ResourceManager.GetObject("SearchResult", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to back to main.
        /// </summary>
        internal static string Shell_GoToMain {
            get {
                return ResourceManager.GetString("Shell_GoToMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  of .
        /// </summary>
        internal static string Shell_ItemCounterSeperator {
            get {
                return ResourceManager.GetString("Shell_ItemCounterSeperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backspace.
        /// </summary>
        internal static string Shell_Keyboard_Backspace {
            get {
                return ResourceManager.GetString("Shell_Keyboard_Backspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Shell_Keyboard_Cancel {
            get {
                return ResourceManager.GetString("Shell_Keyboard_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ch -.
        /// </summary>
        internal static string Shell_Keyboard_ChannelDown {
            get {
                return ResourceManager.GetString("Shell_Keyboard_ChannelDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ch +.
        /// </summary>
        internal static string Shell_Keyboard_ChannelUp {
            get {
                return ResourceManager.GetString("Shell_Keyboard_ChannelUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string Shell_Keyboard_Done {
            get {
                return ResourceManager.GetString("Shell_Keyboard_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Shortcuts:.
        /// </summary>
        internal static string Shell_Keyboard_Instructions1 {
            get {
                return ResourceManager.GetString("Shell_Keyboard_Instructions1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0=Space | Clear=Backspace | Back=Cancel | Play=Done.
        /// </summary>
        internal static string Shell_Keyboard_Instructions2 {
            get {
                return ResourceManager.GetString("Shell_Keyboard_Instructions2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space.
        /// </summary>
        internal static string Shell_Keyboard_Space {
            get {
                return ResourceManager.GetString("Shell_Keyboard_Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show onscreen keyboard.
        /// </summary>
        internal static string Shell_KeyboardButton {
            get {
                return ResourceManager.GetString("Shell_KeyboardButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log in.
        /// </summary>
        internal static string Shell_Login {
            get {
                return ResourceManager.GetString("Shell_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use either the number keys on your remote or the onscreen keyboard to enter text.
        /// </summary>
        internal static string Shell_LoginMessage {
            get {
                return ResourceManager.GetString("Shell_LoginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Shell_LoginPassword {
            get {
                return ResourceManager.GetString("Shell_LoginPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember my password.
        /// </summary>
        internal static string Shell_LoginRemember {
            get {
                return ResourceManager.GetString("Shell_LoginRemember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Shell_LoginUsername {
            get {
                return ResourceManager.GetString("Shell_LoginUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No image available.
        /// </summary>
        internal static string Shell_NoImage {
            get {
                return ResourceManager.GetString("Shell_NoImage", resourceCulture);
            }
        }
        
        internal static byte[] Styles {
            get {
                object obj = ResourceManager.GetObject("Styles", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ThumbnailButton {
            get {
                object obj = ResourceManager.GetObject("ThumbnailButton", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV.
        /// </summary>
        internal static string TV {
            get {
                return ResourceManager.GetString("TV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view all {0} tv shows.
        /// </summary>
        internal static string TV_Category_SubTitle {
            get {
                return ResourceManager.GetString("TV_Category_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, Season {1}
        ///{2}
        ///{3} min, {4}, {5}.
        /// </summary>
        internal static string TV_Details_Metadata {
            get {
                return ResourceManager.GetString("TV_Details_Metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all.
        /// </summary>
        internal static string TV_Filter_All {
            get {
                return ResourceManager.GetString("TV_Filter_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV Not Configured.
        /// </summary>
        internal static string TV_NotSetUpDialog_Caption {
            get {
                return ResourceManager.GetString("TV_NotSetUpDialog_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must set up TV before using this feature..
        /// </summary>
        internal static string TV_NotSetUpDialog_Text {
            get {
                return ResourceManager.GetString("TV_NotSetUpDialog_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This TV show is now scheduled to record..
        /// </summary>
        internal static string TV_RecordDialog_Text {
            get {
                return ResourceManager.GetString("TV_RecordDialog_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Scheduled.
        /// </summary>
        internal static string TV_RecordDialog_ViewScheduled {
            get {
                return ResourceManager.GetString("TV_RecordDialog_ViewScheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV Episode.
        /// </summary>
        internal static string TV_Search_Type_Episode {
            get {
                return ResourceManager.GetString("TV_Search_Type_Episode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV Show.
        /// </summary>
        internal static string TV_Search_Type_Show {
            get {
                return ResourceManager.GetString("TV_Search_Type_Show", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ZLogo_Full {
            get {
                object obj = ResourceManager.GetObject("ZLogo_Full", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ZLogo_Left {
            get {
                object obj = ResourceManager.GetObject("ZLogo_Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ZLogo_Right {
            get {
                object obj = ResourceManager.GetObject("ZLogo_Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ZLogoProgramLibrary {
            get {
                object obj = ResourceManager.GetObject("ZLogoProgramLibrary", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
